// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXWX8mnhbVXj_F_C7udTfhkbuuV54HAck',
    appId: '1:297128897427:web:5e0b9f1fa7551117f9d666',
    messagingSenderId: '297128897427',
    projectId: 'chatapp-f51d1',
    authDomain: 'chatapp-f51d1.firebaseapp.com',
    storageBucket: 'chatapp-f51d1.firebasestorage.app',
    measurementId: 'G-YZ5R5MR68E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ZiTV8We1e1PhwHJtysQIh3iEbi_K8EQ',
    appId: '1:297128897427:android:1fca20941ee5486ff9d666',
    messagingSenderId: '297128897427',
    projectId: 'chatapp-f51d1',
    storageBucket: 'chatapp-f51d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPftM3KasAOWCzyuT-vp-Hqv9ChgVDmIc',
    appId: '1:297128897427:ios:550d6043c5106ae0f9d666',
    messagingSenderId: '297128897427',
    projectId: 'chatapp-f51d1',
    storageBucket: 'chatapp-f51d1.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPftM3KasAOWCzyuT-vp-Hqv9ChgVDmIc',
    appId: '1:297128897427:ios:550d6043c5106ae0f9d666',
    messagingSenderId: '297128897427',
    projectId: 'chatapp-f51d1',
    storageBucket: 'chatapp-f51d1.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXWX8mnhbVXj_F_C7udTfhkbuuV54HAck',
    appId: '1:297128897427:web:71a10bb55753bc05f9d666',
    messagingSenderId: '297128897427',
    projectId: 'chatapp-f51d1',
    authDomain: 'chatapp-f51d1.firebaseapp.com',
    storageBucket: 'chatapp-f51d1.firebasestorage.app',
    measurementId: 'G-J1S8RE2HBX',
  );
}
